"""Changed recipe_name field to not be unique

Revision ID: 2135c3b693fd
Revises: f2d570cb2108
Create Date: 2022-01-30 20:04:36.048333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2135c3b693fd'
down_revision = 'f2d570cb2108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_recipe_name', table_name='recipe')
    op.create_index(op.f('ix_recipe_recipe_name'), 'recipe', ['recipe_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_recipe_name'), table_name='recipe')
    op.create_index('ix_recipe_recipe_name', 'recipe', ['recipe_name'], unique=False)
    # ### end Alembic commands ###
