"""Added Ingredient Table, Recipe Table has one-to-many relationship to Ingredient Table

Revision ID: 4a3dd4164a1a
Revises: 8015d35d0796
Create Date: 2022-01-28 20:06:32.616433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3dd4164a1a'
down_revision = '8015d35d0796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient', sa.String(length=128), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    # ### end Alembic commands ###
