"""Added Description column to Recipe model

Revision ID: d410d18f71df
Revises: 4a3dd4164a1a
Create Date: 2022-01-28 20:17:38.734109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd410d18f71df'
down_revision = '4a3dd4164a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'description')
    # ### end Alembic commands ###
