"""Converted prep_time and cook_time columns in Recipe to integers, times will be stored as seconds

Revision ID: f2d570cb2108
Revises: d410d18f71df
Create Date: 2022-01-29 12:47:32.391461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d570cb2108'
down_revision = 'd410d18f71df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('step_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    # ### end Alembic commands ###
